### ISSUE TITLE
README

### ISSUE THREAD

**Issue by oponder** [giantswarm/draughtsman#12]
The readme should explain a couple of things.

- Where does this project live in the over all scheme of things?
- How do I get started with it?  A simple invocation or example with output of what it does is always handy.
- How do I run the tests? (Even if it is 'known' how to do it, it is always nice to have a reminder for others, and sometimes there are some tags, or special things you expect people to set up before running the test. This should be documented as well)

We have a template for this: https://github.com/giantswarm/example-opensource-repo

You can pick out what makes most sense to you. leave out the future steps and stuff if it's not clear yet.

**Comment by argais** [comment]
A simple issue like this has no answers or no comments after more than half an year?
I stumbled upon this project today and the readme doesnt even explain exactly what this does (deployment agent.. yay.. so?).. there is no link to a blog post or anything...

**Comment by oponder** [comment]
Hey @argais, `draughtsman` is something we use internally heavily, and did not expect many other people to be interested in yet. So this issue did not get prioritized. Your comment gives us an idea that at least someone else is interested.

We have some internal documentation we can adapt to try and clarify what this project actually does.

In a nutshell though: It runs in your cluster, listens for github deployment events, and turns them into `helm upgrade` commands that get sent to `tiller`, also running in your cluster.

Does that sound like what you were looking for?

**Comment by argais** [comment]
That sounds like a concise explanation, exactly what I wanted ;) 
can definitely see some use for it in a couple projects, will give it a shot now. thanks!

**Comment by oponder** [comment]
Ok! Good luck!

There isn't much experience yet on what happens when other people try to run draughtsman, there might be some assumptions we have baked in here.

In any case, I'll try to get the documentation updated this week to better explain things.

**Comment by argais** [comment]
Thanks, if I have any feedback, once I get to give it a try, I'll open an issue :)

**Comment by oponder** [comment]
I don't think we'll be improving the README much more any time soon. We're already internally working towards a different workflow for our deployments.

Closing stale issues that I created.
