### ISSUE TITLE
Latest draughtsman builds don't work correctly (at least on gauss)

### ISSUE THREAD

**Issue by tuommaki** [giantswarm/draughtsman#64]
When re-installing draughtsman on gauss, I hit an issue where it crashes as follows:

`{"caller":"github.com/giantswarm/draughtsman/vendor/github.com/giantswarm/operatorkit/client/k8s/k8s.go:99","debug":"creating in-cluster config","time":"2018-01-31 14:38:21.883"}
{"caller":"github.com/giantswarm/draughtsman/service/configurer/configmap/configmap.go:69","debug":"checking connection to Kubernetes","time":"2018-01-31 14:38:21.978"}
{"caller":"github.com/giantswarm/draughtsman/service/configurer/secret/secret.go:69","debug":"checking connection to Kubernetes","time":"2018-01-31 14:38:21.990"}
{"caller":"github.com/giantswarm/draughtsman/service/installer/helm/helm.go:193","debug":"logging into registry","registry":"quay.io","time":"2018-01-31 14:38:21.998","username":"giantswarm+gauss"}
{"caller":"github.com/giantswarm/draughtsman/service/installer/helm/helm.go:163","debug":"running helm command","name":"login","time":"2018-01-31 14:38:21.998"}
{"caller":"github.com/giantswarm/draughtsman/service/installer/helm/helm.go:175","debug":"ran helm command","name":"login","stderr":"Error: unknown command \"registry\" for \"helm\"\nRun 'helm --help' for usage.\n","stdout":"","time":"2018-01-31 14:38:23.285"}
panic: Error: unknown command "registry" for "helm"
Run 'helm --help' for usage.
: exit status 1

goroutine 1 [running]:
main.main.func1(0xc4200ea3c0, 0xc4200eaa50, 0xc42019cf00)
       /go/src/github.com/giantswarm/draughtsman/main.go:114 +0xbad
github.com/giantswarm/draughtsman/vendor/github.com/giantswarm/microkit/command/daemon.(*command).Execute(0xc4201ceae0, 0xc420500240, 0xc42041e880, 0x0, 0x4)
       /go/src/github.com/giantswarm/draughtsman/vendor/github.com/giantswarm/microkit/command/daemon/command.go:122 +0x195
github.com/giantswarm/draughtsman/vendor/github.com/giantswarm/microkit/command/daemon.(*command).Execute-fm(0xc420500240, 0xc42041e880, 0x0, 0x4)
       /go/src/github.com/giantswarm/draughtsman/vendor/github.com/giantswarm/microkit/command/daemon/command.go:75 +0x52
github.com/giantswarm/draughtsman/vendor/github.com/spf13/cobra.(*Command).execute(0xc420500240, 0xc42041e800, 0x4, 0x4, 0xc420500240, 0xc42041e800)
       /go/src/github.com/giantswarm/draughtsman/vendor/github.com/spf13/cobra/command.go:651 +0x23d
github.com/giantswarm/draughtsman/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420500900, 0x15a3f80, 0x2a, 0xc4201a3570)
       /go/src/github.com/giantswarm/draughtsman/vendor/github.com/spf13/cobra/command.go:726 +0x2fe
github.com/giantswarm/draughtsman/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420500900, 0xc420500900, 0x28)
       /go/src/github.com/giantswarm/draughtsman/vendor/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
       /go/src/github.com/giantswarm/draughtsman/main.go:226 +0x134d`

This looks like Helm registry plugin is not deployed there. I tried couple older and the first one that worked was this build: 

**1.0.0-5f16808642df8b9e10ee64345e965a62a9603816** **December 27 2017**

**Comment by pipo02mix** [comment]
It is solved downgrading the helm version in the host cluster. For some unknown reason `gauss` had running tiller with version `2.7.2` meanwhile `draughtsman` client has 2.6.2.

**Comment by kopiczko** [comment]
The same thing just happened in `gollum`.
